"""empty message

Revision ID: ffd548e625ae
Revises: 0ffc07b49fbf
Create Date: 2024-05-31 14:22:30.427349

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ffd548e625ae'
down_revision = '0ffc07b49fbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('role_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('role_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
